baseurl = "https://matcornic.github.io/hugo-learn-doc"
languageCode = "en-us"
title = "Hugo Learn Theme"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"
canonifyurls = true

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/docs/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
